name=ပၵ်းယဵမ်ႈဝၼ်းၶႄႇ
month.1=လိူၼ်ထူၼ်ႈၼိုင်ႈ
month.2=လိူၼ်ထူၼ်ႈသွင်
month.3=လိူၼ်ထူၼ်ႈသၢမ်
month.4=လိူၼ်ထူၼ်ႈသီႇ
month.5=လိူၼ်ထူၼ်ႈႁႃႈ
month.6=လိူၼ်ထူၼ်ႈႁူၵ်း
month.7=လိူၼ်ထူၼ်ႈၸဵတ်း
month.8=လိူၼ်ထူၼ်ႈပႅတ်ႇ
month.9=လိူၼ်ထူၼ်ႈၵဝ်ႈ
month.10=လိူၼ်ထူၼ်ႈသိပ်း
month.11=လိူၼ်ထူၼ်ႈသိပ်းဢဵတ်း
month.12=လိူၼ်ထူၼ်ႈသိပ်းသွင်
