name=chinese
month.1=M01
month.2=M02
month.3=M03
month.4=M04
month.5=M05
month.6=M06
month.7=M07
month.8=M08
month.9=M09
month.10=M10
month.11=M11
month.12=M12
zodiac.1=zi
zodiac.2=chou
zodiac.3=yin
zodiac.4=mao
zodiac.5=chen
zodiac.6=si
zodiac.7=wu
zodiac.8=wei
zodiac.9=shen
zodiac.10=you
zodiac.11=xu
zodiac.12=hai
