name=кинески\ календар
month.1=M01
month.2=M02
month.3=M03
month.4=M04
month.5=M05
month.6=M06
month.7=M07
month.8=M08
month.9=M09
month.10=M10
month.11=M11
month.12=M12
solarTerm.1=spring\ begins
solarTerm.2=rain\ water
solarTerm.3=insects\ awaken
solarTerm.4=spring\ equinox
solarTerm.5=bright\ and\ clear
solarTerm.6=grain\ rain
solarTerm.7=summer\ begins
solarTerm.8=grain\ full
solarTerm.9=grain\ in\ ear
solarTerm.10=summer\ solstice
solarTerm.11=minor\ heat
solarTerm.12=major\ heat
solarTerm.13=autumn\ begins
solarTerm.14=end\ of\ heat
solarTerm.15=white\ dew
solarTerm.16=autumn\ equinox
solarTerm.17=cold\ dew
solarTerm.18=frost\ descends
solarTerm.19=winter\ begins
solarTerm.20=minor\ snow
solarTerm.21=major\ snow
solarTerm.22=winter\ solstice
solarTerm.23=minor\ cold
solarTerm.24=major\ cold
