name=کومبڠ\ چينا
month.1=M01
month.2=M02
month.3=M03
month.4=M04
month.5=M05
month.6=M06
month.7=M07
month.8=M08
month.9=M09
month.10=M10
month.11=M11
month.12=M12
month.narrow.1=1
month.narrow.2=2
month.narrow.3=3
month.narrow.4=4
month.narrow.5=5
month.narrow.6=6
month.narrow.7=7
month.narrow.8=8
month.narrow.9=9
month.narrow.10=10
month.narrow.11=11
month.narrow.12=12
