name=Sĩnẽj\ Prỹg-kurã-kar
month.1=1-Kysã
month.2=2-Kysã
month.3=3-Kysã
month.4=4-Kysã
month.5=5-Kysã
month.6=6-Kysã
month.7=7-Kysã
month.8=8-Kysã
month.9=9-Kysã
month.10=10-Kysã
month.11=11-Kysã
month.12=12-Kysã
month.narrow.1=1K
month.narrow.2=2K
month.narrow.3=3K
month.narrow.4=4K
month.narrow.5=5K
month.narrow.6=6K
month.narrow.7=7K
month.narrow.8=8K
month.narrow.9=9K
month.narrow.10=10K
month.narrow.11=11K
month.narrow.12=12K
