name=chinese
month.1=M01
month.2=M02
month.3=M03
month.4=M04
month.5=M05
month.6=M06
month.7=M07
month.8=M08
month.9=M09
month.10=M10
month.11=M11
month.12=M12
month.narrow.1=1
month.narrow.2=2
month.narrow.3=3
month.narrow.4=4
month.narrow.5=5
month.narrow.6=6
month.narrow.7=7
month.narrow.8=8
month.narrow.9=9
month.narrow.10=10
month.narrow.11=11
month.narrow.12=12
month.leapPattern={0}bis
solarTerm.1=spring\ begins
solarTerm.2=rain\ water
solarTerm.3=insects\ awaken
solarTerm.4=spring\ equinox
solarTerm.5=bright\ and\ clear
solarTerm.6=grain\ rain
solarTerm.7=summer\ begins
solarTerm.8=grain\ full
solarTerm.9=grain\ in\ ear
solarTerm.10=summer\ solstice
solarTerm.11=minor\ heat
solarTerm.12=major\ heat
solarTerm.13=autumn\ begins
solarTerm.14=end\ of\ heat
solarTerm.15=white\ dew
solarTerm.16=autumn\ equinox
solarTerm.17=cold\ dew
solarTerm.18=frost\ descends
solarTerm.19=winter\ begins
solarTerm.20=minor\ snow
solarTerm.21=major\ snow
solarTerm.22=winter\ solstice
solarTerm.23=minor\ cold
solarTerm.24=major\ cold
sexagenary.1=jia-zi
sexagenary.2=yi-chou
sexagenary.3=bing-yin
sexagenary.4=ding-mao
sexagenary.5=wu-chen
sexagenary.6=ji-si
sexagenary.7=geng-wu
sexagenary.8=xin-wei
sexagenary.9=ren-shen
sexagenary.10=gui-you
sexagenary.11=jia-xu
sexagenary.12=yi-hai
sexagenary.13=bing-zi
sexagenary.14=ding-chou
sexagenary.15=wu-yin
sexagenary.16=ji-mao
sexagenary.17=geng-chen
sexagenary.18=xin-si
sexagenary.19=ren-wu
sexagenary.20=gui-wei
sexagenary.21=jia-shen
sexagenary.22=yi-you
sexagenary.23=bing-xu
sexagenary.24=ding-hai
sexagenary.25=wu-zi
sexagenary.26=ji-chou
sexagenary.27=geng-yin
sexagenary.28=xin-mao
sexagenary.29=ren-chen
sexagenary.30=gui-si
sexagenary.31=jia-wu
sexagenary.32=yi-wei
sexagenary.33=bing-shen
sexagenary.34=ding-you
sexagenary.35=wu-xu
sexagenary.36=ji-hai
sexagenary.37=geng-zi
sexagenary.38=xin-chou
sexagenary.39=ren-yin
sexagenary.40=gui-mao
sexagenary.41=jia-chen
sexagenary.42=yi-si
sexagenary.43=bing-wu
sexagenary.44=ding-wei
sexagenary.45=wu-shen
sexagenary.46=ji-you
sexagenary.47=geng-xu
sexagenary.48=xin-hai
sexagenary.49=ren-zi
sexagenary.50=gui-chou
sexagenary.51=jia-yin
sexagenary.52=yi-mao
sexagenary.53=bing-chen
sexagenary.54=ding-si
sexagenary.55=wu-wu
sexagenary.56=ji-wei
sexagenary.57=geng-shen
sexagenary.58=xin-you
sexagenary.59=ren-xu
sexagenary.60=gui-hai
zodiac.1=zi
zodiac.2=chou
zodiac.3=yin
zodiac.4=mao
zodiac.5=chen
zodiac.6=si
zodiac.7=wu
zodiac.8=wei
zodiac.9=shen
zodiac.10=you
zodiac.11=xu
zodiac.12=hai
